### ISSUE TITLE
Verifying one state per test

### ISSUE THREAD

**Issue by imbusy** [SEEK-Jobs/pact-go#26]
We had a problem where we had multiple states for a consumer-producer pair, but it was difficult to write setup and teardown methods for each state on the producer side and we preferred to keep only one state per test for readability.

We had to rewrite the provider verification part of the library to accommodate our use case and the fork is here: https://github.com/imbusy/pact-go

With this rewrite, you provide one state per test in the ProviderState method and after all the tests are run, verify that all states are tested using the VerifyAllStatesTested method in the final teardown method.

This update touches only the producer tests. Nothing on the consumer side changes.

Any comments on this approach?

**Comment by gsblue** [comment]
I can understand where you are coming from. What if there was a method "VerifyState(providerState string)" on the provider/producer side which only verifies a particular provider state?

The .NET pact library has handled this use case by doing something similar.

**Comment by imbusy** [comment]
Yeah, the VerifyState would make the interface cleaner by merging ProviderState with Verify. I will update my fork to add this method.

We still have to verify whether all states were verified once all tests are run in the teardown method so we don't miss something. This is already implemented in the fork above.

**Comment by gsblue** [comment]
You could use this to verify each state in different tests. By using "TestMain" function to build PactFileVerifier and then tear it down after the tests are finished. The code may look something like this:
```
var (
  v Verifier
)

func TestMain(m *testing.M) {
  server := httptest.NewServer(handler)
  u, _ := url.Parse(server.URL)
  v = NewPactFileVerifier(nil, nil, nil).
		HonoursPactWith("client").
		PactUri("./pact-file.json", nil).
		ServiceProvider("api", &http.Client{}, u)
  
  outputCode := m.Run()
  
  if err := v.Verify(); err != nil {
    outputCode = 1
    fmt.Println(err)
  }
  server.Close()
  os.Exit(outputCode) 
}

func TestFirstState(t *testing.T) {
  v.ProviderState("there is a user with id {23}", nil, nil)
  if err := v.Verify("", "there is a user with id {23}"); err != nil {
    t.Error(err)
  }
}

func TestSecondState(t *testing.T) {
  v.ProviderState("there is no user with id {200}", nil, nil)
  if err := v.Verify("", "there is no user with id {200}"); err != nil {
    t.Error(err)
  }
}

```

**Comment by imbusy** [comment]
That is essentially what we do now.
